spring.application.name=studentmgnt
spring.datasource.url=jdbc:mysql://localhost:3306/sample
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Sarayu@1609
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true	
server.port=8081